name: build-reusable

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14

      - name: build-src
        run: yarn build

      - name: build-app
        run: yarn package

      - name: upload-artifacts
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: actions/upload-artifact@v3
        with:
          name: executables
          path: packages/executables/
          retention-days: 1
