name: build-release

on: [push, pull_request]

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14

      - name: build-src
        run: yarn build

      - name: build-and-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: yarn release
