name: build-release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build-template.yml

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ls
      - name: upload-artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: packages/executables/
