name: release
on:
  release:
    types: [published, unpublished]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14

      - name: build-src
        run: yarn build

      - name: release
        run: yarn release
