name: build-release

on:
  release:
    types: [published]

jobs:
  build-release:
    uses: ./.github/workflows/build-template.yml

    steps:
      - name: upload-artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: packages/executables/
