name: release-app

on: [release]

jobs:
  release-app:
    runs-on: ubuntu-latest

    steps:
      - name: yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14

      - name: build-src
        run: yarn build

      - name: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: yarn release
