name: test-and-build

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14

      - name: build-src
        run: yarn build

      - name: build-electron-app
        run: yarn package
